baseURL = "https://rgbg.github.io/"
languageCode = "en-us"
title = "Rajendra Gandhi Business Group"
theme = "mango"
publishDir = "docs"

[params]
company = "Rajendra Gandhi Business Group"

[menu]

[[menu.main]]
name = "Email"
pre = "mail"
url = "mailto:rajensgandhi@gmail.com"
weight = 1

[[menu.main]]
name = "WhatsApp"
pre = "smartphone"
url = "https://wa.me/919227260331"
weight = 2
